### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by ricaragao** [jb-cbd/meteor-bootstrap3-typeahead#1]
Can you put some examples to us ?

**Comment by jb-cbd** [comment]
Hello, this repo is a simple wrap up of bootstrap3-typeahead for Meteor.
You can find good examples on how to use it on the original repo here : https://github.com/bassjobsen/Bootstrap-3-Typeahead
And if you want to use it with Bootstrap Tagsinput : http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/
Hope that helps, 
Cheers,
JB
